In [130]:
import numpy

In [131]:
array1=numpy.array([2,4,5,1,8,9])

In [132]:
type(array1)

numpy.ndarray

In [133]:
array1.shape

(6,)

In [134]:
print(array1)

[2 4 5 1 8 9]


In [135]:
array2=numpy.full(5,2)

In [136]:
print(array2)

[2 2 2 2 2]


In [137]:
array3=numpy.ones(3,dtype=int)
print(array3)

[1 1 1]


In [138]:
array4=numpy.random.random(6)
print(array4)

[0.8672115  0.68648196 0.3373084  0.27237827 0.25984533 0.7422527 ]


In [139]:
array5=numpy.random.randint(2,7)
print(array5)

2


In [140]:
array1=numpy.arange(3,17,3)
print(array1)

[ 3  6  9 12 15]


# 인덱싱, 슬라이싱

In [141]:
array1=numpy.array([1,2,3,4,5,6,8,9])

In [142]:
array1[-1]

9

* 인덱싱 파이썬 리스트로 하기

In [143]:
array1[[1,3,4]]

array([2, 4, 5])

* **인덱싱 __array__ 활용**해서 하기

In [144]:
array2=numpy.array([2,1,3])

In [145]:
array1[array2]

array([3, 2, 4])

* array __슬라이싱__

In [146]:
array1[1:7]

array([2, 3, 4, 5, 6, 8])

In [147]:
array1[:6]

array([1, 2, 3, 4, 5, 6])

In [148]:
array1[2:5:2]

array([3, 5])

# numpy 기본 연산

In [149]:
array1=numpy.arange(10)
array2=numpy.arange(10,20)

In [150]:
array1+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [151]:
array1+array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [152]:
array1/array2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421])

In [153]:
array1**array2

array([          0,           1,        4096,     1594323,   268435456,
         452807053,  -683606016, -2094633337,           0,  -400556711],
      dtype=int32)

# 흥부부대찌개 매출 계산

In [154]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

revenue_in_dollar = [
    1200, 1600, 1400, 1300, 
    2100, 1400, 1500, 2100, 
    1500, 1500, 2300, 2100, 
    2800, 2600, 1700, 1400, 
    2100, 2300, 1600, 1800, 
    2200, 2400, 2100, 2800, 
    1900, 2100, 1800, 2200, 
    2100, 1600, 1800
]

In [155]:
yen=numpy.array(revenue_in_yen)
dollar=numpy.array(revenue_in_dollar)

In [156]:
won=yen*10.08+dollar*1138

In [157]:
won.astype(int)

array([4389600, 5248000, 4818800, 5108200, 6825000, 3004400, 3521400,
       5817000, 5033400, 4630200, 5439800, 6220200, 4900000, 4370000,
       4253000, 5524400, 6421800, 6145400, 5651200, 3560400, 3612400,
       5150400, 6220200, 7016800, 5589400, 6623400, 3560400, 3814000,
       6018600, 5046400, 4568400])

# numpy boolean 연산 
### boolean 값 이용해서 필터링하기

In [158]:
array_b=numpy.array([2,3,5,7,11,13,17,19,23,29,32])

In [159]:
array_b>4

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [160]:
array_b%2==0

array([ True, False, False, False, False, False, False, False, False,
       False,  True])

In [161]:
booleans=numpy.array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [162]:
numpy.where(booleans) # np.where(condition, true-value, false-value)

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int64),)

In [163]:
filter=numpy.where(booleans)

In [164]:
array_b[filter]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 32])

### 흥부부대찌개 목표 일 매출에 미달되는 매출만 모아보기

In [165]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

In [166]:
array_r=numpy.array(revenue_in_yen)
booleans=array_r<=200000

In [168]:
bad_days=numpy.where(booleans)

In [169]:
bad_days

(array([ 5,  6, 12, 13, 19, 20, 26, 27], dtype=int64),)

In [172]:
array_r[bad_days]

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

# 기본적인 통계 기능

In [174]:
import numpy as np

In [175]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

print(array1.max()) # 최댓값
print(array1.min()) # 최솟값

31
5


In [176]:
print(array1.mean()) # 평균값

15.25


In [177]:
print(np.median(array1)) # 중앙값, 중앙값은 특이하게 numpy array 메소드가 아닌 numpy 메소드임

13.5


In [178]:
print(array1.std()) # 표준 편차
print(array1.var()) # 분산

8.496322733983215
72.1875
